{{- if .Values.felix.tls.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "calico-node.fullname" . }}
  labels:
    {{- include "calico-node.fullname" . | nindent 4 }}
type: kubernetes.io/tls
data:
  ca.crt: {{ .Values.felix.tls.ca | b64enc }}
  tls.crt: {{ .Values.felix.tls.cert | b64enc }}
  tls.key: {{ .Values.felix.tls.key | b64enc }}
{{- end }}
