tools:
  github:
  - name: local

  helm:
  - name: in-docker
    cmd:
    - |-
      docker run -it --rm \
        -w $(pwd) \
        -v $(pwd):$(pwd) \
        ghcr.io/arhat-dev/helm:v3.6.2 \
        /helm

shells:
- name: bash

github:release:
- name: charts
  title@template: chart-release-{{ now | date "2006-01-02" }}
  draft: true
  files:
  - path: .packages/*.tgz

helm:package:
- name: charts
  chart: charts/*
  packages_dir: &pkg_dir .packages
  signing:
    enabled: false

helm:index:
- name: charts
  hooks:
    before:
    - shell: git switch gh-pages
    after:success:
    - shell: |-
        mv .packages/index.yaml ./index.yaml
        git add ./index.yaml
        git commit -m "chore: Update chart index"
        git push
    after:
    - shell: |-
        echo "going back to ${GIT_BRANCH}"
        git switch ${GIT_BRANCH}

  packages_dir: *pkg_dir
  repo_url@template: |-
    https://github.com/arhat-dev/helm-charts/releases/
    {{- /* just a comment for multi-line formatting */ -}}
    download/chart-release-{{ now | date "2006-01-02" }}/
  merge: ./index.yaml
