tools:
  github:
  - name: local
    use_shell: true
    shell_name: bash

  helm:
  - name: in-docker
    cmd@env:
    - docker
    - run
    - -i
    - --rm
    - -w
    - $(pwd)
    - -v
    - $(pwd):$(pwd)
    # source(docker): ghcr.io/arhat-dev/helm
    - ghcr.io/arhat-dev/helm:3.6
    - /helm

  workflow:
  - name: local

shells:
- name: bash

workflow:run:
- name: release-chart-to-github
  hooks:
    before:
    - name: Fetch history
      shell: git fetch --prune --unshallow
      continue_on_error: true

    - name: Lint charts
      shell: make lint.all

    - shell: |-
        git config --global user.email '72795724+arhatbot@users.noreply.github.com'
        git config --global user.name 'Arhat Bot'

  jobs:
  - task: helm:in-docker:package(charts)
  - task: github:local:release(charts)
  - task: helm:in-docker:index(charts)

github:release:
- name: charts
  hooks:
    before:
    - shell:bash: |-
        tag_name="chart-release-${GIT_COMMIT:0:8}"
        git tag -m "${tag_name}" "${tag_name}"
        git push origin "${tag_name}"

  title@template: chart-release-{{ .Env.GIT_COMMIT | substr 0 8 }}
  tag@template: chart-release-{{ .Env.GIT_COMMIT | substr 0 8 }}
  notes@env: |-
    Automated chart release

    for commit ${GIT_COMMIT}

  draft: false
  files:
  - path: ./.packages/*.tgz

helm:package:
- name: charts
  chart: charts/*
  packages_dir: &pkg_dir .packages
  signing:
    enabled: false

helm:index:
- name: charts
  hooks:
    before:
    - shell: git switch gh-pages
    after:success:
    - shell: |-
        cat .packages/index.yaml
        sudo mv .packages/index.yaml ./index.yaml

        git add ./index.yaml
        git commit -m "chore: Update chart index"
        git push

    after:
    - shell@env: |-
        echo "going back to ${GIT_BRANCH}"
        git switch ${GIT_BRANCH}

  packages_dir: *pkg_dir
  repo_url@template: |-
    https://github.com/arhat-dev/helm-charts/releases/
    {{- /* just a comment for multi-line formatting */ -}}
    download/chart-release-{{ .Env.GIT_COMMIT | substr 0 8 }}/
  merge: ./index.yaml
