# exclude: |
#   (?x)^(
#     file-regex-pattern-1|
#     file-regex-pattern-2
#   )$

repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.5.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-yaml
