apiVersion: v1
kind: Secret
metadata:
  name: {{ include "sonar-badge-proxy.fullname" . }}
  labels:
    {{- include "sonar-badge-proxy.labels" . | nindent 4 }}
type: Opaque
data:
  AUTHORIZATION: {{ .Values.config.sonarqube_user_token | b64enc }}
  SECRET: {{ .Values.config.token_secret | b64enc }}
