apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "aranya.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "aranya.labels" . | nindent 4 }}
data:
  config.yaml: |
    {{- tpl (toYaml .Values.config) $ | nindent 4 }}
