apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ksync.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ksync.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "ksync.selectorLabels" . | nindent 6 }}
  template:
    metadata:
    {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        {{- include "ksync.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "ksync.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      volumes:
        - name: config
          configMap:
            name: {{ include "ksync.fullname" . }}
      containers:
        - name: ksync
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
          - /ksync
          - -c
          - /etc/ksync/config.yaml
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          volumeMounts:
            - name: config
              mountPath: /etc/ksync/config.yaml
              subPath: config.yaml
          {{- if .Values.config.ksync.metrics.enabled }}
          ports:
            - name: metrics
              containerPort: {{ index (split ":" (default ":9876" .Values.config.ksync.metrics.listen)) "_1" }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: {{ .Values.config.ksync.metrics.httpPath }}
              port: metrics
          readinessProbe:
            httpGet:
              path: {{ .Values.config.ksync.metrics.httpPath }}
              port: metrics
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
