{{- if eq .Values.datastore "etcd" }}
# The following contains k8s Secrets for use with a TLS enabled etcd cluster.
# For information on populating Secrets, see http://kubernetes.io/docs/user-guide/secrets/
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: calico-etcd-secrets
  namespace: kube-system
data:
  {{- if .Values.etcd.tls.enabled }}
  etcd-key: {{ .Values.etcd.tls.key | b64enc }}
  etcd-ca: {{ .Values.etcd.tls.caCert | b64enc }}
  etcd-cert: {{ .Values.etcd.tls.cert | b64enc }}
  {{- end }}
{{- end }}
