apiVersion: v1
kind: Secret
metadata:
  name: {{ include "opendj.fullname" . }}-admin
  labels:
    {{- include "opendj.labels" . | nindent 4 }}
data:
  ROOT_USER_DN: {{ .Values.config.ldap.admin.userDN | b64enc }}
  ROOT_PASSWORD: {{ .Values.config.ldap.admin.password | b64enc }}
