apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "opendj.fullname" . }}
  labels:
    {{- include "opendj.labels" . | nindent 4 }}
spec:
  serviceName: {{ include "opendj.fullname" . }}
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "opendj.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "opendj.selectorLabels" . | nindent 8 }}
    spec:
      terminationGracePeriodSeconds: 1800
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: opendj
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          envFrom:
            - secretRef:
                name: {{ include "opendj.fullname" . }}-admin
          env:
            - name: BASE_DN
              value: {{ .Values.config.ldap.baseDN }}
            - name: MASTER_SERVER
              value: {{ .Values.config.replication.master }}
          ports:
            {{- if .Values.service.ports.snmp }}
            - name: snmp
              containerPort: 2161
              protocol: UDP
            {{- end }}
            {{- if .Values.service.ports.ldap }}
            - name: ldap
              containerPort: 1389
              protocol: TCP
            {{- end }}
            {{- if .Values.service.ports.ldaps }}
            - name: ldaps
              containerPort: 1636
              protocol: TCP
            {{- end }}
            {{- if .Values.service.ports.management }}
            - name: management
              containerPort: 4444
              protocol: TCP
            {{- end }}
            {{- if .Values.service.ports.jmx }}
            - name: jmx
              containerPort: 1689
              protocol: TCP
            {{- end }}
          {{- if .Values.service.ports.ldap }}
          livenessProbe:
            exec:
              command:
                - ldapsearch
                - --port
                - "1389"
                - --baseDN
                - cn=monitor
                - (cn=userRoot backend)
              initialDelaySeconds: 60
          readinessProbe:
            exec:
              command:
                - ldapsearch
                - --port
                - "1389"
                - --baseDN
                - cn=monitor
                - (cn=userRoot backend)
              initialDelaySeconds: 30
          {{- end }}
          volumeMounts:
            - mountPath: /opt/opendj/data/
              name: ${OPENDJ_SERVICE_NAME}-data
            - mountPath: /opt/opendj/import-data/
              name: import-data
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
  volumeClaimTemplates:
    - metadata:
        name: {{ include "opendj.fullname" . }}-data
      spec:
        {{ if .Values.persistence.storageClass }}
        storageClassName: {{ .Values.persistence.storageClass }}
        {{- end }}
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: {{ .Values.persistence.capacity }}
