apiVersion: v1
kind: Secret
metadata:
  name: {{ include "abbot.fullname" . }}
  labels:
    {{- include "abbot.labels" . | nindent 4 }}
type: Opaque
data:
  config.yaml: {{ .Values.config | toYaml | b64enc }}
