# Default values for ksync.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

nameOverride: ""
fullnameOverride: ""

nodeSelector: {}
tolerations: []
affinity: {}

imagePullSecrets: []
image:
  repository: docker.io/arhatdev/ksync
  pullPolicy: IfNotPresent
  tag: latest

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}
podSecurityContext: {}
securityContext:
  capabilities:
    drop:
    - ALL
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 1000

resources:
  requests:
    cpu: 100m
    memory: 64Mi
  # limits:
  #   cpu: 100m
  #   memory: 128Mi

serviceMonitor:
  # create service monitor for prometheus operator
  create: false

config:
  ksync:
    namespaced: true
    log:
    - level: debug
      format: console
      file: stderr
    metrics:
      enabled: true
      listen: :9876
      httpPath: /metrics
    leaderElection:
      # default to the pod name
      #identity: ""

      # lease options
      lease:
        expiration: 10s
        renewTimeout: 3s
        retryInterval: 1s
        expiryToleration: 10s

      # lock options
      lock:
        # default to ksync-leader-election
        #name:
        type: leases
        # default to pod namespace
        #namespace:

    kubeClient:
      # kubeconfig file path, will fallback to in cluster config if not specified
      #kubeconfig: ""
      rateLimit:
        enabled: false
        qps: 5
        burst: 10
