apiVersion: v2
name: calico
description: BGP only calico helm chart for Kubernetes
type: application
maintainers:
- name: arhat-dev
  email: dev@arhat.dev
keywords:
- kubernetes
- network
- calico
- bgp
- controller
- typha
icon: https://docs.projectcalico.org/images/felix_icon.png
home: https://www.projectcalico.org
sources:
- https://github.com/projectcalico/calico
- https://github.com/projectcalico/kube-controllers
- https://github.com/projectcalico/typha
- https://github.com/arhat-dev/helm-charts
version: 0.1.4
# docker-image: docker.io/calico/kube-controllers
appVersion: v3.16.5
