{{- if .Values.typha.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "calico.typha.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "calico.typha.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.typha.replicas | default 1 }}
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      {{- include "calico.typha.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "calico.typha.selectorLabels" . | nindent 8 }}
      annotations:
        cluster-autoscaler.kubernetes.io/safe-to-evict: 'true'
    spec:
      # Since Calico can't network a pod until Typha is up, we need to run Typha itself
      # as a host-networked pod.
      hostNetwork: true
      {{- with .Values.typha.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.typha.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.typha.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "calico.typha.fullname" . }}
      priorityClassName: system-cluster-critical
      # fsGroup allows using projected serviceaccount tokens as described here kubernetes/kubernetes#82573
      securityContext:
        fsGroup: 65534
      {{- if .Values.typha.tls.enabled }}
      volumes:
      - name: felix-typha-tls
        secret:
          secretName: {{ include "calico.typha.fullname" . }}
          defaultMode: 0400
      {{- end }}
      securityContext:
        runAsNonRoot: true
        allowPrivilegeEscalation: false
      containers:
        - name: typha
          image: {{ .Values.typha.image.repo }}:{{ .Values.typha.image.tag | default .Chart.AppVersion }}
          {{- if .Values.typha.tls.enabled }}
          volumeMounts:
            - name: felix-typha-tls
              mountPath: /etc/felix-typha
          {{- end }}
          ports:
            - containerPort: {{ .Values.typha.port | default 5473 }}
              name: typha
              protocol: TCP
          env:
            {{- if .Values.bpf.enabled }}
            # Overrides for kubernetes API server host/port. Needed in BPF mode.
            - name: KUBERNETES_SERVICE_HOST
              value: {{ .Values.bpf.kubernetesAPI.host | quote }}
            - name: KUBERNETES_SERVICE_PORT
              value: {{ .Values.bpf.kubernetesAPI.port | quote }}
            {{- end }}
            - name: TYPHA_LOGSEVERITYSCREEN
              value: {{ .Values.typha.logLevel | default "info" | quote }}
            # disable file logging
            - name: TYPHA_LOGFILEPATH
              value: "none"
            - name: TYPHA_LOGSEVERITYSYS
              value: "none"
            - name: TYPHA_CONNECTIONREBALANCINGMODE
              value: "kubernetes"
            - name: TYPHA_DATASTORETYPE
              value: "kubernetes"
            - name: TYPHA_HEALTHENABLED
              value: "true"
            {{- if .Values.typha.useNodePodCIDR }}
            - name: USE_POD_CIDR
              value: "true"
            {{- end }}
            {{- if .Values.typha.metrics.enabled }}
            # Uncomment these lines to enable prometheus metrics. Since Typha is host-networked,
            # this opens a port on the host, which may need to be secured.
            - name: TYPHA_PROMETHEUSMETRICSENABLED
              value: "true"
            - name: TYPHA_PROMETHEUSMETRICSPORT
              value: {{ .Values.typha.metrics.port | quote }}
            {{- end }}
          {{- if .Values.typha.tls.enabled -}}
            {{- if and (not .Values.typha.tls.felixURISAN) (not .Values.typha.tls.felixCommonName) -}}
            {{ fail "must specify at lease one of felixURISAN and felixCommonName" }}
            {{- end -}}
            {{- if .Values.typha.tls.felixCommonName }}
            - name: TYPHA_CLIENTCN
              value: {{ .Values.typha.tls.felixCommonName }}
            {{- end }}
            {{- if .Values.typha.tls.felixURISAN }}
            - name: TYPHA_CLIENTURISAN
              value: {{ .Values.typha.tls.felixURISAN }}
            {{- end }}
            - name: TYPHA_CAFILE
              value: /etc/felix-typha/ca.crt
            - name: TYPHA_SERVERCERTFILE
              value: /etc/felix-typha/tls.crt
            - name: TYPHA_SERVERKEYFILE
              value: /etc/felix-typha/tls.key
          {{- end }}
      readinessProbe:
        httpGet:
          path: /readiness
          port: 9098
          host: localhost
        periodSeconds: 10
      livenessProbe:
        httpGet:
          path: /liveness
          port: 9098
          host: localhost
        periodSeconds: 30
        initialDelaySeconds: 30
{{- end }}
