{{- if .Values.typha.enabled -}}
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: {{ include "calico.typha.fullname" . }}
  namespace: kube-system
  labels:
    {{- include "calico.typha.labels" . | nindent 4 }}
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      {{- include "calico.typha.selectorLabels" . | nindent 6 }}
{{- end -}}
