{{- if and .Values.typha.enabled .Values.typha.tls.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "calico.typha.fullname" . }}
  labels:
    {{- include "calico.typha.fullname" . | nindent 4 }}
type: kubernetes.io/tls
data:
  ca.crt: {{ .Values.typha.tls.ca | b64enc }}
  tls.crt: {{ .Values.typha.tls.cert | b64enc }}
  tls.key: {{ .Values.typha.tls.key | b64enc }}
{{- end }}
