{{- if .Values.typha.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "calico.typha.fullname" . }}
  namespace: kube-system
  labels:
    {{- include "calico.typha.labels" . | nindent 4 }}
spec:
  ports:
  - port: 5473
    protocol: TCP
    targetPort: typha
    name: typha
  selector:
    {{- include "calico.typha.selectorLabels" . | nindent 4 }}
{{- end }}
