{{- if and (eq .Values.datastore "kubernetes") .Values.typha.enabled -}}
# This manifest creates a Service, which will be backed by Calico's Typha daemon.
# Typha sits in between Felix and the API server, reducing Calico's load on the API server.
apiVersion: v1
kind: Service
metadata:
  name: {{ include "calico.typha.fullname" . }}
  namespace: kube-system
  labels:
    {{- include "calico.typha.labels" . | nindent 4 }}
spec:
  ports:
  - port: 5473
    protocol: TCP
    targetPort: calico-typha
    name: calico-typha
  selector:
    {{- include "calico.typha.selectorLabels" . | nindent 4 }}
{{- end -}}
