replicaCount: 1

nameOverride: ""
fullnameOverride: ""

nodeSelector: {}
tolerations: []
affinity: {}
podAnnotations: {}

image:
  repository: ghcr.io/arhat-dev/sonar-badge-proxy
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: latest

imagePullSecrets: []

podSecurityContext: {}
  # fsGroup: 2000
securityContext:
  capabilities:
    drop:
    - ALL
  readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  className: ""
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: sonar-badge-proxy.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
  #  - secretName: sonar-badge-proxy-tls
  #    hosts:
  #      - sonar-badge-proxy.local

resources: {}
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

config:
  sonarqube_endpoint: http://sonarqube:8080
  authorization_header_value: BASIC user:pass
  listen_port: 8080
  # token == md5("$PROJECT:$SECRET")
  token_secret: secret-used-to-md5-hash-project-for-public-token-generation
  # https://github.com/tynn/sonar-badge-proxy#metric-mapping
  exposed_metrics:
  - status
  - bugs
  - codesmells
  - coverage
  - duplications
  - lines
  - maintainability
  - reliability
  - security
  - techdept
  - vulnerabilities

  tls:
    insecure_skip_verify: false
