{{- if and .Values.ingress.enabled (semverCompare ">=1.19-0" .Capabilities.KubeVersion.GitVersion) -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "renovate-server.fullname" . }}
  labels:
    {{- include "renovate-server.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.ingress.tls }}
  tls:
    {{- range .Values.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    {{- range .Values.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ . }}
            backend:
              service:
                name: {{ include "renovate-server.fullname" $ }}
                port: {{ $.Values.service.port }}
          {{- end }}
    {{- end }}
{{- end }}
