apiVersion: v1
kind: Secret
metadata:
  name: {{ include "renovate-server.fullname" . }}
  labels:
    {{- include "renovate-server.labels" . | nindent 4 }}
type: Opaque
data:
  config.yaml: {{ .Values.config | toYaml | b64enc }}
