{{- if .Values.pluginRegistry.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "plugin-registry.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "plugin-registry.selectorLabels" . | nindent 4 }}
data:
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "plugin-registry.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "plugin-registry.labels" . | nindent 4 }}
spec:
  revisionHistoryLimit: 2
  strategy:
    type: Recreate
  replicas: {{ .Values.pluginRegistry.replicaCount }}
  selector:
    matchLabels:
      {{- include "plugin-registry.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.pluginRegistry.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "plugin-registry.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.pluginRegistry.podSecurityContext | nindent 8 }}
      containers:
        - name: plugin-registry
          securityContext:
            {{- toYaml .Values.pluginRegistry.securityContext | nindent 12 }}
          image: {{ include "plugin-registry.image" . }}
          imagePullPolicy: {{ .Values.pluginRegistry.image.pullPolicy }}
          envFrom:
            - configMapRef:
                name: {{ include "plugin-registry.fullname" . }}
                optional: true
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /v3/plugins/
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 3
          readinessProbe:
            httpGet:
              path: /v3/plugins/
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 3
            periodSeconds: 10
            timeoutSeconds: 3
          resources:
            {{- toYaml .Values.pluginRegistry.resources | nindent 12 }}
      {{- with .Values.pluginRegistry.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.pluginRegistry.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.pluginRegistry.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "plugin-registry.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "plugin-registry.selectorLabels" . | nindent 4 }}
spec:
  type: {{ .Values.pluginRegistry.service.type }}
  ports:
    - port: {{ .Values.pluginRegistry.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "plugin-registry.selectorLabels" . | nindent 4 }}
---
{{- if .Values.pluginRegistry.ingress.enabled -}}
{{- $fullName := include "plugin-registry.fullname" . -}}
{{- $svcPort := .Values.pluginRegistry.service.port -}}
{{- if and .Values.pluginRegistry.ingress.className (not (semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion)) }}
  {{- if not (hasKey .Values.pluginRegistry.ingress.annotations "kubernetes.io/ingress.class") }}
  {{- $_ := set .Values.pluginRegistry.ingress.annotations "kubernetes.io/ingress.class" .Values.pluginRegistry.ingress.className}}
  {{- end }}
{{- end }}
{{- if semverCompare ">=1.19-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1
{{- else if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ $fullName }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "plugin-registry.labels" . | nindent 4 }}
  {{- with .Values.pluginRegistry.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if and .Values.pluginRegistry.ingress.className (semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion) }}
  ingressClassName: {{ .Values.pluginRegistry.ingress.className }}
  {{- end }}
  {{- if .Values.pluginRegistry.ingress.tls }}
  tls:
    {{- range .Values.pluginRegistry.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    {{- range .Values.pluginRegistry.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            {{- if and .pathType (semverCompare ">=1.18-0" $.Capabilities.KubeVersion.GitVersion) }}
            pathType: {{ .pathType }}
            {{- end }}
            backend:
              {{- if semverCompare ">=1.19-0" $.Capabilities.KubeVersion.GitVersion }}
              service:
                name: {{ $fullName }}
                port:
                  number: {{ $svcPort }}
              {{- else }}
              serviceName: {{ $fullName }}
              servicePort: {{ $svcPort }}
              {{- end }}
          {{- end }}
    {{- end }}
{{- end }}

{{- end }}
