# See https://github.com/projectcalico/kube-controllers
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "calico.kube-controllers.fullname" . }}
  namespace: kube-system
  labels:
    {{- include "calico.kube-controllers.labels" . | nindent 4 }}
spec:
  # The controllers can only have a single active instance.
  replicas: 1
  selector:
    matchLabels:
      {{- include "calico.kube-controllers.selectorLabels" . | nindent 6 }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        {{- include "calico.kube-controllers.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.kubeControllers.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.kubeControllers.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.kubeControllers.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "calico.kube-controllers.fullname" . }}
      priorityClassName: system-cluster-critical
      containers:
      - name: kube-controllers
        image: {{ .Values.kubeControllers.image.repo }}:{{ .Values.kubeControllers.image.tag | default .Chart.AppVersion }}
        env:
        # kubernetes datastore only supports node controller
        - name: ENABLED_CONTROLLERS
          value: node
        - name: LOG_LEVEL
          value: {{ .Values.kubeControllers.logLevel | default "info" | quote }}
        - name: DATASTORE_TYPE
          value: kubernetes
        - name: AUTO_HOST_ENDPOINTS
          value: "enabled"
        readinessProbe:
          exec:
            command:
            - /usr/bin/check-status
            - -r
