apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "calico.kube-controllers.fullname" . }}
  namespace: {{ .Release.Namespace }}
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "calico.kube-controllers.fullname" . }}
rules:
# Nodes are watched to monitor for deletions.
- apiGroups: [""]
  resources:
  - nodes
  verbs:
  - watch
  - list
  - get
# Pods are queried to check for existence.
- apiGroups: [""]
  resources:
  - pods
  verbs:
  - get
# IPAM resources are manipulated when nodes are deleted.
- apiGroups: ["crd.projectcalico.org"]
  resources:
  - ippools
  verbs:
  - list
- apiGroups: ["crd.projectcalico.org"]
  resources:
  - blockaffinities
  - ipamblocks
  - ipamhandles
  verbs:
  - get
  - list
  - create
  - update
  - delete
# kube-controllers manages hostendpoints.
- apiGroups: ["crd.projectcalico.org"]
  resources:
  - hostendpoints
  verbs:
  - get
  - list
  - create
  - update
  - delete
# Needs access to update clusterinformations.
- apiGroups: ["crd.projectcalico.org"]
  resources:
  - clusterinformations
  verbs:
  - get
  - create
  - update
# KubeControllersConfiguration is where it gets its config
- apiGroups: ["crd.projectcalico.org"]
  resources:
  - kubecontrollersconfigurations
  verbs:
  # read its own config
  - get
  # create a default if none exists
  - create
  # update status
  - update
  # watch for changes
  - watch
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "calico.kube-controllers.fullname" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "calico.kube-controllers.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "calico.kube-controllers.fullname" . }}
  namespace: {{ .Release.Namespace }}
