apiVersion: v1
kind: Secret
metadata:
  name: {{ include "arhat.fullname" . }}
  labels:
    {{- include "arhat.labels" . | nindent 4 }}
type: Opaque
data:
  config.yaml: {{ .Values.config | toYaml | b64enc }}
{{- if and .Values.config.extension.enabled .Values.runtime.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "arhat.fullname" . }}-runtime
  labels:
    {{- include "arhat.labels" . | nindent 4 }}
type: Opaque
data:
  runtime-config.yaml: {{ .Values.runtime.config | toYaml | b64enc }}
{{- end }}
