name: release

# yamllint disable-line rule:truthy
on:
  workflow_dispatch:
    inputs:
      reason:
        description: reason to run this workflow
        required: false
        default: test
  check_run:
    types:
    - rerequested
    - requested_action
  pull_request:
    branches:
    - master
  push:
    paths:
    - charts/**
    branches:
    - master

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Lint
      run: make lint.all

    - name: Install helm
      uses: azure/setup-helm@v1
      with:
        version: latest

    - uses: actions/setup-go@v2
      with:
        go-version: 1.16.x

    - uses: arhat-dev/actions-setup-dukkha@master

    - name: Test Gerneration
      run: |
        dukkha workflow local run test-gen

    - name: Release Chart
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |-
        dukkha workflow local run release-chart-to-github
